services:
  backend:
    image: emmaallain06/backend:latest
    container_name: backend
    ports:
      - "8081:8080"
    restart: always
  frontend:
      image: emmaallain06/frontend:latest
      container_name: frontend
      ports:
        - "3000:3000"
      depends_on:
        - backend
      restart: always
