name: Build & Push Front/Back Docker Images

on:
  push:
    branches: [ main, feat/devops ]  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Build & Push Front React
    - name: Build & Push Front (React)
      uses: docker/build-push-action@v5
      with:
        context: ./front-end/
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

    # 4. Build & Push Back (Maven)
    - name: Build & Push Back (Maven)
      uses: docker/build-push-action@v5
      with:
        context: ./back-end/
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mon-back:latest
