name: Build & Push Front/Back Docker Images

on:
  push:
    branches: [ main, feat/devops, feat/devops-front ]  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Build & Push Front React
    - name: Build & Push Front (React)
      uses: docker/build-push-action@v5
      with:
        context: ./front-end
        file: ./front-end/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        build-args: |
          VITE_API_BASE=https://api.lucidarena.tech/api
          VITE_WS_BASE=wss://api.lucidarena.tech/ws
          VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}

        # 4. Build & Push Back (Maven)
    - name: Build & Push Back (Maven)
      uses: docker/build-push-action@v5
      with:
        context: ./back-end/
        file: ./back-end/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        build-args: |
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
